module.exports = {
  apps: [
    {
      name: 'mcp-panel-server',
      script: 'dist/api-server/src/index.js',
      cwd: './api-server',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 9810,
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 9810,
      },
      log_date_format: 'YYYY-MM-DD HH:mm Z',
      error_file: './logs/api-server-error.log',
      out_file: './logs/api-server-out.log',
      log_file: './logs/api-server-combined.log',
      time: true,
    },
    {
      name: 'mcp-panel-client',
      script: 'node',
      args: 'server.js',
      cwd: './web-app',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 9811,
        HOST: '127.0.0.1',
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 9811,
        HOST: '127.0.0.1',
      },
      log_date_format: 'YYYY-MM-DD HH:mm Z',
      error_file: './logs/web-app-error.log',
      out_file: './logs/web-app-out.log',
      log_file: './logs/web-app-combined.log',
      time: true,
    },
  ],
};
